#version: "3.9"
#
#services:
#  app:
#    build: .
#    container_name: calorie-app-container
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./data:/app/data
#    env_file:
#      - .env
#    restart: always
version: "3.9"

services:
  app:
    build: .
    container_name: calorie-app-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: calorie-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calorie_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: